# -- 1
# SELECT SNAME, CITY FROM S;
# -- 2
# SELECT PNAME, COLOR, WEIGHT FROM P;
# -- 3
# SELECT JNO FROM SPJ WHERE SNO='S1';
# -- 4
# SELECT PNAME, SUM(QTY) FROM P, SPJ WHERE P.PNO=SPJ.PNO AND SPJ.JNO='J2' GROUP BY PNAME;
# -- 5
# SELECT DISTINCT PNO FROM SPJ WHERE SNO IN (SELECT SNO FROM S WHERE CITY='上海');
# -- 6
# SELECT JNAME FROM J WHERE JNO IN (SELECT JNO FROM SPJ WHERE SNO IN  (SELECT SNO FROM S WHERE CITY='上海'));
# -- 7
# SELECT DISTINCT JNO FROM J WHERE NOT EXISTS(
#     SELECT * FROM SPJ WHERE SPJ.JNO=J.JNO AND SNO IN (SELECT SNO FROM S WHERE S.CITY='天津')
#     );
-- 8
UPDATE P SET COLOR='蓝' WHERE COLOR='红';
-- 9
UPDATE SPJ SET SNO='S3' WHERE SNO='S5' AND JNO='J4' AND PNO='P6';
-- 10
DELETE FROM SPJ WHERE SNO='S2';
DELETE FROM S WHERE SNO='S2';
-- 11
INSERT INTO SPJ (SNO, JNO, PNO, QTY) VALUES('S2','J6','P4',200);