-- 1
SELECT DISTINCT SNO FROM SPJ WHERE JNO='J1';
-- 2
SELECT SNO FROM SPJ WHERE JNO='J1' AND PNO='P1';
-- 3
SELECT SNO FROM SPJ WHERE JNO='J1' AND PNO IN (SELECT PNO FROM P WHERE COLOR='红');
-- 4
SELECT JNO FROM J WHERE NOT EXISTS(
    SELECT * FROM SPJ WHERE
        SPJ.JNO=J.JNO AND SNO IN (SELECT SNO FROM S WHERE CITY='天津') AND PNO IN (SELECT PNO FROM P WHERE COLOR='红')
    );
-- 5
SELECT DISTINCT JNO FROM SPJ SPJX WHERE NOT EXISTS
    (SELECT * FROM SPJ SPJY WHERE SNO='S1' AND NOT EXISTS
        (SELECT * FROM SPJ WHERE JNO=SPJX.JNO AND PNO=SPJY.PNO));

