-- 注释
/*多行注释*/
-- 建立S表
CREATE TABLE S
(
    SNO    CHAR(3) PRIMARY KEY,
    SNAME  VARCHAR(10),
    STATUS CHAR(3),
    CITY   VARCHAR(10)
);

CREATE TABLE P
(
    PNO CHAR(3) PRIMARY KEY ,
    PNAME VARCHAR(10),
    COLOR CHAR(10),
    WEIGHT INT
);

CREATE TABLE J
(
    JNO CHAR(3) PRIMARY KEY ,
    JNAME VARCHAR(10),
    CITY VARCHAR(10)
);

CREATE TABLE SPJ
(
    SNO CHAR(3),
    PNO CHAR(3),
    JNO CHAR(3),
    QTY INT,
    FOREIGN KEY (SNO) REFERENCES S(SNO),
    FOREIGN KEY (PNO) REFERENCES P(PNO),
    FOREIGN KEY (JNO) REFERENCES J(JNO)
);